### ISSUE TITLE
A couple of possible bugs in Chapter2.Rmd

### ISSUE THREAD

**Issue by tjfarrar** [robjhyndman/ETC3550Slides#11]
The file `Chapter2.Rmd` did not compile for me, running R version 4.2.0. There were a couple of minor issues.

One issue was with the line 

```
download.file("http://OTexts.com/fpp3/extrafiles/tourism.xlsx",
              tourism_file <- tempfile())
```

This threw the error, `Error in utils::unzip(zip_path, list = TRUE) : 
  zip file [path] cannot be opened`

I fixed it by including `mode = "wb"` in the `download.file` call. 

Secondly, the code requires the package `fma`, so it should be installed if not already present. Thirdly, the `install.packages` call for `USgas` (and now `fma`) failed on my system due to the CRAN mirror not being explicitly specified - not sure why. When I included `repos = "https://cloud.r-project.org"` in the `install.packages` call, it worked:

```
install.packages(c("USgas", "fma"), dependencies = TRUE, repos = "https://cloud.r-project.org")
```

**Comment by robjhyndman** [comment]
This concerns the solutions files in a different (private) repo, not the slides from this repo.

1. This isn't a problem on Linux, but perhaps it's a Windows issue. In any case, I've amended the solutions to use `mode = "wb"`.
2. Not a bug, but I've now updated the solution to use the graph from the book website, rather than regenerating it.
3. This sounds like a local problem only.
